### ISSUE TITLE
the script hang on 50 mail send

### ISSUE THREAD

**Issue by mostafaamr1** [EyeofEternity/AutoMail#2]
i have smtp mail server with unlimited number of mail sending and the script hang on 50 mail send, i have to restart it again to take another 50.
please can you help here.

**Comment by bridgesign** [comment]
Can you give some more information? I had tested this for hundreds of emails. By the way, if you are using it for organizational purposes you can try using https://github.com/pulsejet/cobalt

**Comment by mostafaamr1** [comment]
Dear Rohan Patil,
Firstly thank you for your reply. Hope you are doing well.

The script runs very well until it reaches the number 50 email and then it hangs and reports the next mails in (fail.txt) so i have to delete what it has done (first 50 mail) and then run the script again. By the way it did not give any error in the terminal or cmd.

Keenly awaiting for your reply

**Comment by mostafaamr1** [comment]
Firstly thank you for your reply. Hope you are doing well.

The script runs very well until it reaches the number 50 email and then it hangs and reports the next mails in (fail.txt) so i have to delete what it has done (first 50 mail) and then run the script again. By the way it did not give any error in the terminal or cmd.

Keenly awaiting for your reply

**Comment by bridgesign** [comment]
I have refactored the whole code. It was one of my early scripts so it was nearly impossible to track detailed problems. Please try out the new script. Now it will display more details on any error. If the problem persists then include the errors printed out.

**Comment by mostafaamr1** [comment]
here is the error that appears:
automail.py:209: DeprecationWarning: 'U' mode is deprecated
  ifile = open(options.file, 'rU')
Traceback (most recent call last):
  File "automail.py", line 229, in <module>
    main()
  File "automail.py", line 218, in main
    session.create_mail(row, row[rec])
  File "automail.py", line 164, in create_mail
    message = message_parse(row, self.content, self.options.pick)
AttributeError: 'smtpsession' object has no attribute 'content'

notes that my command :python automail.py -e 0 -s "example"  -f list.csv
--host "my mail" -m content.html --port 465 --html

**Comment by bridgesign** [comment]
Corrected. Please try now.

**Comment by mostafaamr1** [comment]
that was the first error:
Traceback (most recent call last):
  File "automail.py", line 233, in <module>
    main()
  File "automail.py", line 224, in main
    sleep(random.randint(options.wait, options.wait+10))
NameError: name 'sleep' is not defined

and i change sleep to time.sleep

and here is the second error:
Traceback (most recent call last):
  File "automail.py", line 233, in <module>
    main()
  File "automail.py", line 225, in main
    session.send_email()
TypeError: send_email() missing 1 required positional argument: 'receiver'

notes that my command was: python automail.py -e 0 -s "example"  -f
list.csv --host "my mail" -m content.html --port 465 --html

Keenly awaiting for your reply.

**Comment by bridgesign** [comment]
Corrected both things. Please try now

**Comment by mostafaamr1** [comment]
Thank you it worked and i am trying it till it reaches the 50 and hope it
continues.

*You are the best.*
